services:
  - type: web
    name: office-admin-backend
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm --prefix backend ci
    startCommand: npm --prefix backend start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        value: https://panel.deposist.az,https://deposist.az,https://www.deposist.az

